language: node_js

node_js:
    - "11"
    - "10"
    - "9"
    - "8"

before_script:
    - "npm install -g markdown-link-check"

script:
    - "bash ./check_links.sh"

after_script:
    - "echo ${?}"
